name: deploy

on:
  push:

jobs:

  windows-binaries:

    strategy:
      matrix:
        conf:
         - msvc
         - gnu
        include:
         - conf: msvc
           toolchain: stable
         - conf: gnu
           toolchain: stable-x86_64-pc-windows-gnu

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install stable
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.toolchain }}

    - name: Build cargo-c
      run: |
        cargo build --profile release-strip

    - name: Create zip
      run: |
        cd target/release-strip
        7z a ../../cargo-c-windows-${{ matrix.conf }}.zip `
             "cargo-capi.exe" `
             "cargo-cbuild.exe" `
             "cargo-cinstall.exe"

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: cargo-c-windows-${{ matrix.conf }}-binaries
        path: cargo-c-windows-${{ matrix.conf }}.zip

  linux-binaries:
    strategy:
      fail-fast: false
      matrix:
        target:
         - i686-unknown-linux-musl
         - x86_64-unknown-linux-musl
         - powerpc64le-unknown-linux-gnu
         - aarch64-unknown-linux-musl

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Install cross
      run: |
        cargo install cross --git https://github.com/cross-rs/cross

    - name: Build cargo-c
      run: |
        cross build --target ${{ matrix.target }} \
          --features=vendored-openssl \
          --profile release-strip

    - name: Create zip
      run: |
        cd target/${{ matrix.target }}/release-strip
        tar -czvf $GITHUB_WORKSPACE/cargo-c-${{ matrix.target }}.tar.gz \
                  cargo-capi \
                  cargo-cbuild \
                  cargo-cinstall

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: cargo-c-linux-binaries
        path: cargo-c-${{ matrix.target }}.tar.gz

  linux-binaries-test:
    runs-on: ubuntu-latest
    needs: linux-binaries
    strategy:
      fail-fast: false
      matrix:
        target:
         - i686-unknown-linux-musl
         - x86_64-unknown-linux-musl
         - aarch64-unknown-linux-musl
        include:
          - target: i686-unknown-linux-musl
            platform: i386
          - target: x86_64-unknown-linux-musl
            platform: amd64
          - target: aarch64-unknown-linux-musl
            platform: arm64
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Set up QEMU
        if: matrix.platform != 'i386' && matrix.platform != 'amd64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.platform }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/${{ matrix.platform }}

      - uses: actions/download-artifact@v2
        with:
          name: cargo-c-linux-binaries

      - name: Cache vendored dependencies
        id: cache-vendor-dependencies
        uses: actions/cache@v3
        with:
          path: |
            config.toml
            example-project/vendor
          key: example-project-vendor-${{ hashFiles('example-project/Cargo.toml') }}-${{ matrix.target }}
          restore-keys: |
            example-project-vendor-${{ hashFiles('example-project/Cargo.toml') }}-
            example-project-vendor-

      # Run cargo vendor, because fetching from crates.io in qemu takes too long
      - name: Run cargo vendor on example project
        if: steps.cache-vendor-dependencies.outputs.cache-hit != 'true'
        run: |
          [ -f config.toml ] && cp config.toml ~/.cargo ||:
          cargo vendor \
            --versioned-dirs \
            --manifest-path example-project/Cargo.toml \
            ${{ github.workspace }}/example-project/vendor \
          > config.toml

      - name: Start test container
        run: |
          docker run -d --rm --init \
            --name test \
            -v${{ github.workspace }}:${{ github.workspace }} \
            --workdir ${{ github.workspace }}/example-project \
            --platform linux/${{ matrix.platform }} \
            rust:buster \
            tail -f /dev/null

      - name: Copy file into container
        run: |
          docker cp - test:/usr/local/cargo/bin < cargo-c-${{ matrix.target }}.tar.gz
          docker cp config.toml test:/usr/local/cargo

      - name: Install C API for example project
        run: |
          docker exec test cargo cinstall --offline --verbose --release
          docker exec test ldconfig

      - name: Test usage from C (using Makefile)
        run: |
          docker exec \
            -w ${{ github.workspace }}/example-project/usage-from-c \
            test make
          docker exec test usage-from-c/run_tests

  macos-binaries:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install stable
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Build cargo-c
      run: |
        cargo build --features=vendored-openssl --profile release-strip

    - name: Create zip
      run: |
        cd target/release-strip
        zip $GITHUB_WORKSPACE/cargo-c-macos.zip \
            cargo-capi \
            cargo-cbuild \
            cargo-cinstall

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: cargo-c-macos-binaries
        path: cargo-c-macos.zip

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [windows-binaries, linux-binaries, linux-binaries-test, macos-binaries]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install stable
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Download zip files
      uses: actions/download-artifact@v2

    - name: Create Cargo.lock
      run: |
        cargo update

    - name: Create a release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Cargo.lock
          cargo-c-linux-binaries/*.tar.gz
          cargo-c-macos-binaries/cargo-c-macos.zip
          cargo-c-windows-msvc-binaries/cargo-c-windows-msvc.zip
          cargo-c-windows-gnu-binaries/cargo-c-windows-gnu.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
